### ISSUE TITLE
AttributeError: 'InputLayer' object has no attribute 'output_shape'

### ISSUE THREAD

**Issue by YonatanRA** [paulgavrikov/visualkeras#51]
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[20], line 1
----> 1 visualkeras.layered_view(model)

File /opt/anaconda3/envs/ia/lib/python3.9/site-packages/visualkeras/layered.py:85, in layered_view(model, to_file, min_z, min_xy, max_z, max_xy, scale_z, scale_xy, type_ignore, index_ignore, color_map, one_dim_orientation, background_fill, draw_volume, padding, spacing, draw_funnel, shade_step, legend, font, font_color)
     82 y = min_xy
     83 z = min_z
---> 85 if isinstance(layer.output_shape, tuple):
     86     shape = layer.output_shape
     87 elif isinstance(layer.output_shape, list) and len(
     88         layer.output_shape) == 1:  # drop dimension for non seq. models

AttributeError: 'InputLayer' object has no attribute 'output_shape'
```

**Solution:** Change `output_shape` by `output.shape`

**Comment by jsosniakk** [comment]
@YonatanRA  Any updates on that one?

**Comment by paulgavrikov** [comment]
> @YonatanRA  Any updates on that one?

I merged a PR into main a few days ago. Should be fixed with a clean install from source

**Comment by Sadegh-Kalami** [comment]
thanks for the nice repo!
Thank you for the great repository! However, we are still experiencing a bug identical to the one at the top. we have a bug exactly the same as top.

**Comment by Soontosh** [comment]
@Sadegh-Kalami Sorry for the late response, you'll need to install the latest version via GitHub. Use the following command:
```bash
pip install git+https://github.com/paulgavrikov/visualkeras
```

Marking as resolved
